services:
  postgres:
    container_name: joint_db
    image: postgres
    environment:
      POSTGRES_DB: joint_account
      POSTGRES_USER: joint_account_admin
      POSTGRES_PASSWORD: p;rXG1Y75E

    volumes:
      - joint_data:/var/lib/postgresql/data/

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 7s
      timeout: 3s
      retries: 7

    networks:
      - joint_net

    ports:
      - "5432:5432"

    restart: unless-stopped

  auth:
    container_name: joint_auth
    image: joint_auth:test
    build: ./auth
    environment:
      POSTGRES_HOST: postgres

    depends_on:
      postgres:
        condition: service_healthy
        restart: true

    networks:
      - joint_net

    ports:
      - "8080:8080"

    restart: unless-stopped

  profile:
    container_name: joint_profile
    image: joint_profile:test
    build: ./profile
    environment:
      POSTGRES_HOST: postgres

    depends_on:
      postgres:
        condition: service_healthy
        restart: true

      auth:
        condition: service_started
        restart: false

    networks:
      - joint_net

    ports:
      - "8081:8081"

    restart: unless-stopped

volumes:
  joint_data:

networks:
  joint_net:
    driver: bridge