jwt:
  secret: 984hg493gh0439thr0429guru2309yh937gc763fe87t3f89723gf
  lifetime: 15m
spring:
  security:
    user:
      password: dddf28b9-bc07-4478-bc0c-b399ce0eb716

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

  application:
    name: jointAuth

server:
  port: 8080


